#!/bin/sh

DESKS_MAIN="i ii iii"
DESKS_SEC="I II III"

NUM_MONIT=`bspc query -M | wc -l`
bspc monitor ^1 -d $DESKS_MAIN

if [ "$NUM_MONIT" -gt 1 ]; then
	bspc monitor ^2 -d $DESKS_SEC
fi


bspc config top_padding				14
bspc config -m ^1 bottom_padding	14
bspc config split_ratio				0.50
bspc config border_width			1
bspc config window_gap				12
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config focus_follows_pointer	false
bspc config auto_alternate			true
bspc config auto_cancel				true
bspc config normal_border_color		"#504339"
bspc config active_border_color		"#504339"
bspc config focused_border_color	"#605655"
bspc config presel_border_color		"#990000"
bspc config urgent_border_color		"#FF0066"
bspc config normal_frame_opacity	0.0
bspc config focused_frame_opacity	0.1
bspc config external_rules_command "<%= @home %>/bin/tiling_rules"
