#!/bin/bash
readarray -t PROPS < <(xwinfo -its $1)

INST=${PROPS[0]}
TYPE=${PROPS[1]}
STATE=(${PROPS[2]})

RULE=()

#defaults
case "$TYPE" in
	dock|desktop|notification)	RULE+=("manage=off") ;;
	toolbar|utility)			RULE+=("focus=off") ;;
	desktop)					RULE+=("lower=on") ;;
esac

for s in $STATE; do
	case $s in
		sticky)					RULE+=("sticky=on") ;;
		fullscreen)				RULE+=("fullscreen=on") ;;
	esac
done


#custom rules
case "$INST" in
	google-chrome*|nitrogen|gimp*|ruler)
		RULE+=("floating=on") ;;
	BSPWM_FRAME|bspwm_frame)
		RULE+=("frame=on") ;;
    xmessage)
        RULE+=("manage=off") ;;
esac

echo "${RULE[*]}"
