set nu
set nocompatible
filetype plugin indent on
syntax on
set mouse=a
set backspace=indent,eol,start
set showmatch
set incsearch
set hlsearch
set linespace=0
set ignorecase
set smartcase
set wrap
set autoindent
set shiftwidth=4
set tabstop=4
set softtabstop=4
set expandtab
set showcmd
set smarttab
set nohidden
"set spell
